# Generated by Django 3.2.19 on 2023-07-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('music', 'Music'), ('art', 'Art'), ('gaming', 'Gaming')], default='sections', max_length=20),
        ),
    ]
