# Generated by Django 3.2.19 on 2023-07-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230712_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_credit',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
